# Generated by Django 5.0 on 2023-12-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egroceryapp', '0006_rename_productid_add_to_cart_prodcut_id_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='quantity',
            field=models.IntegerField(default=None, max_length=255),
        ),
    ]
