# Generated by Django 4.1.2 on 2023-12-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egroceryapp', '0007_add_to_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
