# Generated by Django 4.1.2 on 2023-12-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egroceryapp', '0008_alter_add_to_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='product_price',
            field=models.IntegerField(default=None),
        ),
    ]
