# Generated by Django 4.1.2 on 2023-12-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egroceryapp', '0009_add_to_cart_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='subtotal_price',
            field=models.IntegerField(default=None),
        ),
    ]
