# Generated by Django 4.1.2 on 2023-12-13 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egroceryapp', '0011_discount_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_data',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount_data',
            name='total_discounted_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount_data',
            name='total_items_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount_data',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount_data',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
