# Generated by Django 5.0 on 2023-12-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egroceryapp', '0014_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
