# Generated by Django 4.1.2 on 2023-12-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egroceryapp', '0015_remove_profile_district_remove_profile_postname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_All_quantity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
